# Generated by Django 6.1.1 on 2026-10-01 14:36

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Booking',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('phone', models.CharField(max_length=10)),
                ('service', models.CharField(choices=[('Bridal Makeup', 'Bridal Makeup'), ('Party Makeup', 'Party Makeup'), ('Facial & Skincare', 'Facial & Skincare'), ('Hair Styling', 'Hair Styling')], max_length=50)),
                ('date', models.DateField()),
                ('time', models.CharField(choices=[('10:00 AM', '10:00 AM'), ('12:00 PM', '12:00 PM'), ('2:00 PM', '2:00 PM'), ('4:00 PM', '4:00 PM'), ('6:00 PM', '6:00 PM')], max_length=20)),
                ('address', models.TextField()),
                ('status', models.CharField(default='Pending', max_length=20)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
        ),
    ]
