# Generated by Django 6.1.1 on 2026-10-02 10:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bookings', '0002_alter_booking_status'),
    ]

    operations = [
        migrations.AddConstraint(
            model_name='booking',
            constraint=models.UniqueConstraint(condition=models.Q(('status__in', ['Pending', 'Confirmed'])), fields=('date', 'time'), name='unique_active_booking_time'),
        ),
    ]
