# Generated by Django 6.1.1 on 2026-10-06 10:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bookings', '0003_booking_unique_active_booking_time'),
    ]

    operations = [
        migrations.AddField(
            model_name='booking',
            name='cancellation_reason',
            field=models.CharField(blank=True, choices=[('Changed my plans', 'Changed my plans'), ('Found another service', 'Found another service'), ('Booked by mistake', 'Booked by mistake'), ('Not available at this time', 'Not available at this time'), ('Other', 'Other')], default='', max_length=100),
        ),
        migrations.AddField(
            model_name='booking',
            name='reschedule_reason',
            field=models.TextField(blank=True, default=''),
        ),
        migrations.AddField(
            model_name='booking',
            name='updated_at',
            field=models.DateTimeField(auto_now=True),
        ),
    ]
