# Generated by Django 6.1.1 on 2026-10-06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bookings', '0004_booking_cancellation_reason_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='booking',
            name='service',
            field=models.CharField(
                choices=[
                    ('Engagement Makeup', 'Engagement Makeup'),
                    ('Party Makeup', 'Party Makeup'),
                    ('Bridal Makeup', 'Bridal Makeup'),
                    ('Reception Makeup', 'Reception Makeup'),
                    ('Siders Makeup', 'Siders Makeup'),
                    ('HD Bridal Makeup', 'HD Bridal Makeup'),
                    ('Airbrush Makeup', 'Airbrush Makeup'),
                    ('Natural Makeup', 'Natural Makeup'),
                    ('Cocktail Makeup', 'Cocktail Makeup'),
                    ('Festive Makeup', 'Festive Makeup'),
                    ('Baby Shower Makeup', 'Baby Shower Makeup'),
                    ('Photoshoot Makeup', 'Photoshoot Makeup'),
                    ('Facial', 'Facial'),
                    ('Eyebrow', 'Eyebrow'),
                    ('Waxing', 'Waxing'),
                    ('Manicure', 'Manicure'),
                    ('Pedicure', 'Pedicure'),
                    ('Manicure & Pedicure', 'Manicure & Pedicure'),
                    ('Hair Styling', 'Hair Styling'),
                    ('Hair Spa', 'Hair Spa'),
                    ('Bridal Mehendi', 'Bridal Mehendi'),
                    ('Engagement Mehendi', 'Engagement Mehendi'),
                    ('Arabic Mehendi', 'Arabic Mehendi'),
                    ('Minimal Mehendi', 'Minimal Mehendi'),
                    ('Traditional Mehendi', 'Traditional Mehendi'),
                    ('Feet Mehendi', 'Feet Mehendi'),
                ],
                max_length=50,
            ),
        ),
    ]
